### ISSUE TITLE
Worker processes can't use multiprocessing (indirectly prevents usage of scikit-learn and nltk)

### ISSUE THREAD

**Issue by martinth** [celery/billiard#168]
This is a spin off issue from the Celery issue [#1709 Tasks are not allowed to start subprocesses](https://github.com/celery/celery/issues/1709). The Problem was [first mentioned by ostrokach ](https://github.com/celery/celery/issues/1709#issuecomment-122467424) who provided a stack trace that occures when he uses a scikit-learn classifier inside a worker. Since the problem seems to be cause by billiard and not by Celery itself I'm creating a new issue here.
### Stacktrace

```
[2015-07-17 21:23:51,299: ERROR/MainProcess] Task app.f[329d0da4-2e0e-4e1f-8148-d64f47750b1f] raised unexpected: AttributeError("'Worker' object has no attribute '_config'",)
Traceback (most recent call last):
  File "/home/username/anaconda3/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/username/anaconda3/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/username/working/playground/celery/app.py", line 11, in f
    clf = pickle.load(open('clf.pickle', 'rb'))
  File "/home/username/anaconda3/lib/python3.4/site-packages/sklearn/ensemble/__init__.py", line 6, in <module>
    from .base import BaseEnsemble
  File "/home/username/anaconda3/lib/python3.4/site-packages/sklearn/ensemble/base.py", line 13, in <module>
    from ..externals.joblib import cpu_count
  File "/home/username/anaconda3/lib/python3.4/site-packages/sklearn/externals/joblib/__init__.py", line 112, in <module>
    from .parallel import Parallel
  File "/home/username/anaconda3/lib/python3.4/site-packages/sklearn/externals/joblib/parallel.py", line 23, in <module>
    from ._multiprocessing_helpers import mp
  File "/home/username/anaconda3/lib/python3.4/site-packages/sklearn/externals/joblib/_multiprocessing_helpers.py", line 25, in <module>
    _sem = mp.Semaphore()
  File "/home/username/anaconda3/lib/python3.4/multiprocessing/context.py", line 81, in Semaphore
    return Semaphore(value, ctx=self.get_context())
  File "/home/username/anaconda3/lib/python3.4/multiprocessing/synchronize.py", line 127, in __init__
    SemLock.__init__(self, SEMAPHORE, value, SEM_VALUE_MAX, ctx=ctx)
  File "/home/username/anaconda3/lib/python3.4/multiprocessing/synchronize.py", line 59, in __init__
    kind, value, maxvalue, self._make_name(),
  File "/home/username/anaconda3/lib/python3.4/multiprocessing/synchronize.py", line 117, in _make_name
    return '%s-%s' % (process.current_process()._config['semprefix'],
AttributeError: 'Worker' object has no attribute '_config'
```
### To reproduce

Create an empty classifier and save it as a pickle:

```
import pickle
from sklearn.ensemble import GradientBoostingClassifier
clf = GradientBoostingClassifier()
pickle.dump(clf, open('clf.pickle', 'wb'))
```

Create a simple app (`app.py`):

```
import pickle
import sklearn
from celery import Celery

app = Celery(__name__, broker='amqp://localhost//')

@app.task
def f():
    print('hello')
    clf = pickle.load(open('clf.pickle', 'rb'))
    print(clf)
```

Start the celery worker:

```
celery -A app worker --loglevel=debug
```

Run the app:

```
python -c "from app import f; f.delay()"
```

---

I myself also ran into the same error while importing the functions from NLTK (a popular Natural Language Processing library). The problem **only** exists when the code in question is actually run as a worker. It always the problem that the value that is returned by `multiprocessing.current_process()` has no `_config` attribute.

The current workaround for this specific error is:

```
from celery.signals import worker_process_init

@worker_process_init.connect
def fix_multiprocessing(**kwargs):
    from multiprocessing import current_process
    try:
        current_process()._config
    except AttributeError:
        current_process()._config = {'semprefix': '/mp'}
```

However, I'm totally not sure what this might break elsewhere.

---

To me, it looks like the problem was introduced by c7eedbd0ee1498e76d4fa1affac5b1a275660ee7. Prior to that the [`Worker` class](https://github.com/celery/billiard/commit/c7eedbd0ee1498e76d4fa1affac5b1a275660ee7#diff-42cbdfeee4eeeb2688454e975c2d18ffL238) was derived from [`Process`](https://github.com/celery/billiard/blob/master/billiard/process.py#L77) which indeed hat an appropriate `_config` attribute.

**Comment by ask** [comment]
Hmm, but why is current_process() the Worker instance?  The process is started using Process(Worker(...)), so the current_process should still be Process?

**Comment by martinth** [comment]
Because it is set this way in `process.py`. Setter is [here](https://github.com/celery/billiard/blob/4ac42695ce60cdf4786ca36b0cba170a3eb2e12f/billiard/process.py#L48) and the call to it happens [here](https://github.com/celery/billiard/blob/4ac42695ce60cdf4786ca36b0cba170a3eb2e12f/billiard/process.py#L273).

**Comment by ask** [comment]
Yeah, but current_process here is set to `self` and self should be `Process` instance, not `Worker`.

The Worker object is used as the target for the process, and then it copies some attributes over (like inqueue fd, etc, that the celery async pool uses to keep track of things):

https://github.com/scrapy/scrapy/blob/master/scrapy/utils/log.py#L98-L101

So why is `_current_process` a `Worker` instance, and not a `Process` instance?

**Comment by jennaliu** [comment]
Worker inherits from Process, Here is the inheritance tree.
```python
(<class 'celery.concurrency.asynpool.Worker'>, <class 'billiard.pool.Worker'>, <class 'billiard.process.Process'>, <class 'object'>)
```
The following is the stacktrace for where current_process is set to a Worker object.

```shell
...
  /home/junlanvm/anaconda3/lib/python3.5/site-packages/celery-3.1.18-py3.5.egg/celery/bin/worker.py(212)run()
-> state_db=self.node_format(state_db, hostname), **kwargs
  /home/junlanvm/anaconda3/lib/python3.5/site-packages/celery-3.1.18-py3.5.egg/celery/worker/__init__.py(206)start()
-> self.blueprint.start(self)
  /home/junlanvm/anaconda3/lib/python3.5/site-packages/celery-3.1.18-py3.5.egg/celery/bootsteps.py(123)start()
-> step.start(parent)
  /home/junlanvm/anaconda3/lib/python3.5/site-packages/celery-3.1.18-py3.5.egg/celery/bootsteps.py(374)start()
-> return self.obj.start()
  /home/junlanvm/anaconda3/lib/python3.5/site-packages/celery-3.1.18-py3.5.egg/celery/concurrency/base.py(131)start()
-> self.on_start()
  /home/junlanvm/anaconda3/lib/python3.5/site-packages/celery-3.1.18-py3.5.egg/celery/concurrency/prefork.py(117)on_start()
-> **self.options)
  /home/junlanvm/anaconda3/lib/python3.5/site-packages/celery-3.1.18-py3.5.egg/celery/concurrency/asynpool.py(400)__init__()
-> super(AsynPool, self).__init__(processes, *args, **kwargs)
  /home/junlanvm/anaconda3/lib/python3.5/site-packages/billiard-3.3.0.23-py3.5.egg/billiard/pool.py(972)__init__()
-> self._create_worker_process(i)
  /home/junlanvm/anaconda3/lib/python3.5/site-packages/billiard-3.3.0.23-py3.5.egg/billiard/pool.py(1068)_create_worker_process()
-> w.start()
  /home/junlanvm/anaconda3/lib/python3.5/site-packages/billiard-3.3.0.23-py3.5.egg/billiard/process.py(138)start()
-> self._popen = Popen(self)
  /home/junlanvm/anaconda3/lib/python3.5/site-packages/billiard-3.3.0.23-py3.5.egg/billiard/forking.py(105)__init__()
-> code = process_obj._bootstrap()
  /home/junlanvm/anaconda3/lib/python3.5/site-packages/billiard-3.3.0.23-py3.5.egg/billiard/process.py(268)_bootstrap()
-> _set_current_process(self)
> /home/junlanvm/anaconda3/lib/python3.5/site-packages/billiard-3.3.0.23-py3.5.egg/billiard/process.py(54)_set_current_process()
-> _current_process = _mproc._current_process = process
```

Here is the stacktrace where the error occurred.
```shell
...
[2016-10-14 19:13:24,999: WARNING/Worker-2] File "/home/junlanvm/anaconda3/lib/python3.5/site-packages/sklearn/__init__.py", line 57, in <module>
    from .base import clone
[2016-10-14 19:13:25,000: WARNING/Worker-2] File "/home/junlanvm/anaconda3/lib/python3.5/site-packages/sklearn/base.py", line 11, in <module>
    from .utils.fixes import signature
[2016-10-14 19:13:25,000: WARNING/Worker-2] File "/home/junlanvm/anaconda3/lib/python3.5/site-packages/sklearn/utils/__init__.py", line 17, in <module>
    from ..externals.joblib import cpu_count
[2016-10-14 19:13:25,000: WARNING/Worker-2] File "/home/junlanvm/anaconda3/lib/python3.5/site-packages/sklearn/externals/joblib/__init__.py", line 127, in <module>
    from .parallel import Parallel
[2016-10-14 19:13:25,000: WARNING/Worker-2] File "/home/junlanvm/anaconda3/lib/python3.5/site-packages/sklearn/externals/joblib/parallel.py", line 25, in <module>
    from ._multiprocessing_helpers import mp
[2016-10-14 19:13:25,001: WARNING/Worker-2] File "/home/junlanvm/anaconda3/lib/python3.5/site-packages/sklearn/externals/joblib/_multiprocessing_helpers.py", line 25, in <module>
    _sem = mp.Semaphore()
[2016-10-14 19:13:25,001: WARNING/Worker-2] File "/home/junlanvm/anaconda3/lib/python3.5/multiprocessing/context.py", line 81, in Semaphore
    return Semaphore(value, ctx=self.get_context())
[2016-10-14 19:13:25,001: WARNING/Worker-2] File "/home/junlanvm/anaconda3/lib/python3.5/multiprocessing/synchronize.py", line 127, in __init__
    SemLock.__init__(self, SEMAPHORE, value, SEM_VALUE_MAX, ctx=ctx)
[2016-10-14 19:13:25,001: WARNING/Worker-2] File "/home/junlanvm/anaconda3/lib/python3.5/multiprocessing/synchronize.py", line 59, in __init__
    kind, value, maxvalue, self._make_name(),
[2016-10-14 19:13:25,001: WARNING/Worker-2] File "/home/junlanvm/anaconda3/lib/python3.5/multiprocessing/synchronize.py", line 117, in _make_name
    return '%s-%s' % (process.current_process()._config['semprefix'],
<class 'AttributeError'>: 'Worker' object has no attribute '_config'
```

In both stacktraces, I omitted my application specific code at the beginning.

There is no problem with sklearn 0.15.X and versions below. It is introduced by the joblib
https://github.com/scikit-learn/scikit-learn/blob/0.18.X/sklearn/externals/joblib/_multiprocessing_helpers.py

I think the best way to deal with this problem is to set the environment variable JOBLIB_MULTIPROCESSING=0

**Comment by alanjds** [comment]
@auvipy Do this still occur? I saw some comment of you fixing Celery I guess...

**Comment by auvipy** [comment]
@alanjds I think so, as far I remember I merged a pr

**Comment by linar-jether** [comment]
See https://github.com/celery/celery/issues/4551#issuecomment-370386892, joblib now uses `Loky` by default and works fine with celery.
